# Trial number:      137
# HOTA, MOTA, IDF1:  [55.567]
# Группа 1, получила такие параметры для своей постобработки
# одна ошибка

ocsort:
  asso_func: iou
  det_thresh: 0.49428431641933235
  delta_t: 5
  inertia: 0.6758806605183052
  iou_thresh: 0.6247364818234254
  max_age: 7
  min_hits: 7
  use_byte: true

